version: '3'

services:
  mysql:
    image: mariadb:10.5.8
    env_file:
      - ../../tests/tests.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: siphon
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./../mysql/init.sql/:/docker-entrypoint-initdb.d/init.sql

  postgres:
      image: postgres
      env_file:
        - ../../tests/tests.env
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: siphon
      ports:
        - "5432:5432"
      volumes:
        - ./../postgres/:/docker-entrypoint-initdb.d/