name: Run Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Stop MySQL
      run: |
        sudo /etc/init.d/mysql stop
    - name: Initialize Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Tox
      run: pip install tox
    - name: Run Tests with Tox
      run: tox